Log:
  Level: debug
  AccessPath: ./access.log
  ErrorPath: ./error.log
DnsConfigPath: ./dns.json
Nodes:
  -
    PanelType: "V2board"
    ApiConfig:
      ApiHost: "https://trunghau.tk" 
      ApiKey: "trunghau12345678" 
      NodeID: 1 
      NodeType: V2ray 
      Timeout: 30
      EnableVless: false
      EnableXTLS: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      CertConfig:
        CertMode: dns
        CertDomain: "https://trunghau.tk" 
        Provider: cloudflare
        Email: example@lala.im 
        DNSEnv: 
          CLOUDFLARE_EMAIL: crtrunghau@gmail.com
          CLOUDFLARE_API_KEY: 832d5955d123368f11651923a7708917516f2
